language: java
jdk:
- oraclejdk8
dist: trusty
env:
  global:
  - DISPLAY=:99.0
before_deploy:
  - mvn clean install -DskipTests=true
  - ls -l ./com.sap.ims.isa.jcomigrationhelper.updatesite/
  - export BUILD_RES=$(ls ./com.sap.ims.isa.jcomigrationhelper.updatesite/target/*.zip)
  - echo "deploying $BUILD_RES to GitHub releases"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gHGRu9R8HlJmlpJHAFYPBkt3cA2wNEOSfr4fDcHE+DrnaDOPnSKUf2LSFT0cyzVeHhHBpaTWRuS9KHhsuoL4OEa4pJxBX6cU37yyuG8d48hfYQMuNgbdxBVLuHbx0l1uwS0gTqehdYLxspdiZoFVytbInMplaU4hBcGCMLTCp0jR2fgy56H3yZ9XTypthghp8cCNwQjOgLfWxoRUMVy+sitSNjJlS0U6uBQbfPF1kUyi+vnI8bDjNBdUDlb7hfuovCT24dKNlGcPza+RB9OAz96TLhpWDtddbA/B3KBeZZgO9TcqtPOqH52aE8ZvjkfnjVVbQulHMa6Hbi4X80IJFBF3WaZ70SDp8WJchTcVAJKAtAIyZpgSV0BW85tUM9EIvC2+HLdVfnU2lKR9nzuvmcYDBmj8j6LsfbKEZmpdvI2ioReq+0/tduGbod3yVp/Dcjrl0ypaB4qMP0U4fFo+tXMrecmkk7/ucgbiZV9oW6iE3cP624kqudUJpf1SwJvBiCuk9Rxa1yUWF48x1CPMBpcctpNqxbbXgjIEo0EomZ4n3/Iq+fL7ZP14JcFRqogmsgrWhwwl6lN+r1rVnwbrj3rjLRql1kzxJe55lAAcI5xvwZ4J532ZVXkGCfO7owqet+o03ZydmZeUs/v++/Cq37+bWI0hEUONNTjBzI8enQ0=
  file: "${BUILD_RES}"
  on:
    repo: SAP/jcomigrationhelperplugin
